### ISSUE TITLE
Wrong hash output when using Mulithash

### ISSUE THREAD

**Issue by fseffert** [multiformats/cs-multihash#12]
I'm playing around with your library and did the following test:

`
            string encodedString = "This is my text and will be 22333 encoded";
            int nounce = 0;

            var b1 = Encoding.UTF8.GetBytes(encodedString);

            Console.WriteLine("Press enter to start!");
            Console.ReadLine();

            var algo = SHA256.Create();

            while(true)
            {
                var b2 = BitConverter.GetBytes(nounce);

                IEnumerable<byte> allBytes = b2.Concat(b1);

                var hashBytes = Multihash.Sum(HashType.SHA2_256, allBytes.ToArray());
                var hashBytes2 = algo.ComputeHash(allBytes.ToArray());

                string hex = "";

                foreach (byte x in hashBytes2)
                {
                    hex += String.Format("{0:x2}", x);
                }

                Console.WriteLine(hex);
                Console.WriteLine(hashBytes.ToHexString());
                Console.ReadLine();

                nounce++;
            }

`
The output of your implementation is completely different than the built in SHA256 from .NET. What did I do wrong?

**Comment by Stebalien** [comment]
Define "completely different". It should be slightly different because it returns a multihash (self describing hash). See: https://github.com/multiformats/multihash

**Comment by Stebalien** [comment]
This library is for working with self-describing multihashes. If you ask it for a sha256 hash, it *will* return a sha256 hash but it will be wrapped in a multihash "envelope" (which records the hash function (sha256 in this case) and hash length (256)). That way, if you share the hash with someone else, they can check it without having to know if you used sha256, sha512, sha3, etc.

If you *just* want a raw sha256 hash, you'l want to use the built-in sha256 library.

**Comment by tabrath** [comment]
The return type of Multihash.Sum is of type Multihash that have a Digest property which is just the hash you want. That said, I'd do as @Stebalien recommends and use the built-ins or Bouncy Castle if you don't care about the Multihash part.

**Comment by fseffert** [comment]
I see... thank you for your support!
