### ISSUE TITLE
How to add support of Scrypt and Qubit?

### ISSUE THREAD

**Issue by shtse8** [multiformats/cs-multihash#19]
I want o hash these using these two algos.
But cs-multihash cannot suppot at this moment. How can I add support to it?

**Comment by tabrath** [comment]
Well, sure its possible to add support, but neither of those algorithms are currently in the multihash spec. If they one day should be approved in the spec, this library will for sure include support for them.

Head over to github.com/multiformats/multihash and open a issue with your request..
