### ISSUE TITLE
Add netstandard2.0 target

### ISSUE THREAD

**Issue by hanabi1224** [multiformats/cs-multihash#25]
It's recommended to always target netstandard2.0 per https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting

![image](https://user-images.githubusercontent.com/6546635/59160671-11243f00-8b0b-11e9-8c5f-c636d76323cb.png)

**Comment by tabrath** [comment]
I'm totally with you on this, cool thing you've started fixing the issue! 👍

**Comment by tabrath** [comment]
Resolved by #26
