### ISSUE TITLE
Possible to use in a Unity Project?

### ISSUE THREAD

**Issue by edsilv** [multiformats/cs-multihash#9]
Hi,

I'm interested in using this in a Unity v5.5.2f1 project. I tried building it in VS Community 2017 but get (after restoring the NuGet packages):

    The type or namespace name 'Crypto' could not be found (are you missing a using directive or an assembly reference?)

I think I'll need to target .Net 2 or 3.5 for it to work in Unity. From https://github.com/multiformats/cs-multihash/issues/8 it sounds like it only supports 4.6.1?

**Comment by tabrath** [comment]
@edsilv It's unlikely that I will do any work supporting lower net versions as I'm primarely working on the dotnet core implementation. I'm curious tough, what's your use case? Are you depending on the Multihash prefixing?

**Comment by edsilv** [comment]
I'm making a HoloLens app which is using MD5 hashed URLs (sometimes
multiple combined) as keys to use for GameObjects in the WorldAnchorStore.
This works, but I was interested in the potential for using multihash
instead so that these keys could potentially be stored in IPFS at a later
date without needing to be rehashed.

I'm already using IPFS elsewhere in a web based companion app, so it seemed
appealing to use the same hashing algorithm for everything.

I predict that Microsoft will allow devs to override this anchor store with
their own implementations. I think an IPFS one would make a lot of sense if
you were running it on the device. I've mentioned the use cases for IPFS on
HoloLens to @flyingzumwalt and @diasdavid previously. We're loading 3D
objects over the WiFi connection and it would be highly desirable to be
able to store them locally in IPFS and request them from a local gateway.

**Comment by tabrath** [comment]
Will most likely never support versions lower than 4.5. You might look into using the latest Unity versions they are working on using the latest version of Mono these days (experimental at this point), which will support 4.5.
